### ISSUE TITLE
Predator Vision, Thermal Vision bug

### ISSUE THREAD

**Issue by Eriahn** [ArranzCNL/ImprovedCameraSE#100]
Thermal Vision will not show the bright aura surrounding living creatures, or it will show at a very reduced range and rate.

Switching to third person will make thermal vision work as intended.

Tested with and without Improved Camera; without seems to work just fine.

**Comment by Eriahn** [comment]
Update 1: after further testing, thermal vision seems to work as expected while on horse.

**Comment by ArranzCNL** [comment]
Yeah it will do as you are in third person.

Do you know if bQuickLightLighting, fixes the issue whether on or off and report back results? Reason it is off by default is due to Strange Runes and using third person arms. If your on AE I believe you have to switch views after changing the setting.

**Comment by Eriahn** [comment]
Turned bQuickLightLighting on, does solve it partially.

Tested after switching views and game reload, same results. Haven't tried it after a full game restart yet, but I expect it to be the same.

Still feels like the body glow is very damped, getting into 3rd goes full strength again.

I'm indeed using Strange Runes, playing on SE, in case it affects anything.

Edit: On second test, quicklight on or off doesn't make a difference, must been something else that left thermal vision on a, hm, residual state, would be the best way to describe it.

**Comment by Eriahn** [comment]
This is what i mean with residual:

https://user-images.githubusercontent.com/127059599/223125358-59aa4e05-2096-49d6-a93a-0c2ae01524d8.mp4

**Comment by Eriahn** [comment]
Works well enough on interiors thou:

https://user-images.githubusercontent.com/127059599/223135048-216b7ac4-79c2-4e9d-a4cb-9f56b087d576.mp4

**Comment by ArranzCNL** [comment]
I think the top one as its a major city your inside of is why its broken which will be fixed in Hotfix 3, however I have noticed oddity.

Tests have been carried out in first person with and without Improved Camera, as cannot do whatever third does.
- For myself it turns on fine instantly but for other NPC's it seems delayed (Lightfix enabled).
- Re-test with lightfix disabled same result.
- I see what you mean now just looked at my screenshots no like smokey heat source coming off the actors.

Shall carry out more tests hiding behind a wall (forgot to do that).

Edit:
Isolated the issue kind of I know it is coming from 1 of 3 functions... work on a fix for this for hotfix 3 there was another issue I noticed when looking for this bug so I'll fix that as well!

**Comment by Eriahn** [comment]
Glad to hear and be of assistance.

Best to you and your team,  doing an awesome job, truly.

**Comment by ArranzCNL** [comment]
It is funny as @TwistedModding mentioned this to me back along but I couldn't really notice the difference in screenshots. This thermal vision mod makes it stand out like a sore thumb and the isolated function has solved the other lighting issues they spotted! Just means need to find an alternative fix for the third person arms magic effects now :|

**Comment by ArranzCNL** [comment]
Just a brief update I do have it working just need to carry out more testing in regards with third person arms.
_Note: using third person arms will produce the bug, nothing I don't think I can do about that._

**Comment by Eriahn** [comment]
I think that's a fair compromise, especially taking into account that most people that play first person will use the Size Matters animation pack for fp, so won't be an issue for the most part, I think.

**Comment by ArranzCNL** [comment]
I should maybe look into that mod, I just use normal animations in first person.

Anyway bug fixed at long last!

Will be in hotfix 3
