### ISSUE TITLE
Player feet either clip through floor, or floating

### ISSUE THREAD

**Issue by Bulljump** [ArranzCNL/ImprovedCameraSE#101]
When my character does not have any weapons drawn, her feet clip through the floor, sometimes all the way up to the ankles/lower calves. When she has a weapon drawn, her feet float several inches above the floor. Is there a way to fix this?

**Comment by ArranzCNL** [comment]
Only way to really tell is to test various areas, I know slopey areas can cause it and I have seen it myself when I was playing skyrim a couple of weeks ago some of the ground meshes wasn't working correctly it seemed.

You can enabled headbob on the various actions but it is best to turn on smooth animation transitions when you do this otherwise the camera will act snappy, there is a downside you'll get slight inertia.

What race are you using?

**Comment by Bulljump** [comment]
Imperial. I am in Clockwork Castle, which is an area added by a mod, so perhaps that has something to do with it?

**Comment by ArranzCNL** [comment]
Could be best bet is to teleport around various areas using the console, coc LOCATION, for example coc Riverwood.
Just make sure you hard save inside the area your at incase the game tries saving when your using the coc command.

**Comment by Bulljump** [comment]
Confirmed that it was Clockwork Castle. No issues in original Skyrim cells, or in Falskaar cells for that matter.
