### ISSUE TITLE
[SE] Fishing camera locks in first person

### ISSUE THREAD

**Issue by BrotherErryn** [ArranzCNL/ImprovedCameraSE#102]
Saw a previous bug for this that said Hotfix 1 resolved this. I redownloaded the release here (says Hotfix 2) to attempt to fix, but no change. As in the original ticket, after fishing the camera is locked a pseudo-first person mode. Toggling TFC fixes it. I haven't modified the config from the base install and have double-checked that nothing is overriding it.

Note that _unlike_ the original ticket, I'm still on SE, not AE, but with the CC Fishing mod.

**Comment by ArranzCNL** [comment]
You'll have to wait for the source to be released to have this fixed I'm afraid as I am not personally messing with my current setup just to get that installed for 1.5.97.

**Comment by ArranzCNL** [comment]
@BrotherErryn 

TwistedModding has this installed and has no issues, make sure your on Hotfix 2. It frees itself fine.

**Comment by BrotherErryn** [comment]
@ArranzCNL Dumb question; that's just the single 7z release package on this repo, right? It's just marked PR 5 but the changelog indicates Hotfix 2. If so, that's the one I installed.

**Comment by ArranzCNL** [comment]
Aye it is but on that side of things nothing has changed inside of hotfix 3 (which TwistedModding is running) although the plugin is possibly running faster. I remember it getting stuck when testing on AE due to ForceFirstPerson/Third which is mitigated in hotfix 2.

Reset State should free you but I'd prefer that as a last resort option as in something that rarely happens and you have to use it.

It could be just Hotfix 3 somehow solves it (would be interested to know) as I know it has solved the Clear Skies shout issue which is strange but whatever fixed without intervention :D

Hotfix 3 should be released on the 12th March 2023 - I just have to fix GameOverlay stuff.
