### ISSUE TITLE
Unable to click in menu

### ISSUE THREAD

**Issue by Kara-bit** [ArranzCNL/ImprovedCameraSE#107]
The menu shows up when using Shift+Home but unable to click anything, using keys (Such as ctrl s) works but still unable to click. SSE, 1.5.97.0.8 2.0.20. Tried with no reshade and reshade. Is there a file that can be edited to change camera settings?

**Comment by ArranzCNL** [comment]
Sometimes that happens, I use to get it personally on the debug build but after hotfix 3 I haven't had it since debug/release the only thing that fixed it was just rebooting the game. I shall have to look into the mouse though since I didn't realise the keys were actually still working!

You can set MenuMode=1 mouse will work 100% of the time.

Or manually edit:
Copy Default.ini (inside of profiles) and paste back into same folder and rename to your choosing.
Change the settings how you want.
Edit ImprovedCameraSE.ini at the bottom change ProfileName= to point to your new ini file (case sensitive)
