### ISSUE TITLE
CTD when enabled through Vortex

### ISSUE THREAD

**Issue by Welkin52** [ArranzCNL/ImprovedCameraSE#118]
I have patched a downgrade for Skyrim SE from 1.6.640 to 1.5.97.0 per instructions for using with OStim, so ostensibly it should work. Have followed all installation guidelines for OStim. When ImprovedCamera is enabled, the program crashes to desktop immediately upon launch. I am wondering if this current version of ImprovedCameraSE is new compared to what worked for them before or what could be causing the issue. They provide an ini file for use with OStim. When I disable ImprovedCameraSE the program does not CTD and mostly seems to work ok. Anyhow, thought you should know.

**Comment by ArranzCNL** [comment]
Disable menumode inside of ImprovedCameraSE.ini or try it on 1.

Essentially you have an external overlay running which is hooking D3D11CreateDeviceAndSwapChain due to this it is capturing the dummy device which gets destroyed hence the crash. I haven't found a solution to stop this from happening as of yet.
