### ISSUE TITLE
Game will not open

### ISSUE THREAD

**Issue by murderman2** [ArranzCNL/ImprovedCameraSE#123]
Thank you for your efforts at making a fantastic mod! I am a fan of you. Moving on, I have an issue with your mod. The game does not launch when menumode is set to 2 in the ini file. I assume this is because I do not have reshade. I think people who don't use reshade would find it helpful to know changing the menumode value to 1 or 0 in the ini will resolve this issue. If the game will not launch without reshade, then reshade should be listed in the requirements section. You say that it is only a requirement if certain mods are enabled, but my experience contradicts that. I had no other mods enabled and the issue persisted. I also cleansed the overwrite folder. Keep in mind I had SKSE build 2.0.20 correctly installed throughout this troubleshooting process.

**Comment by murderman2** [comment]
Also made sure I was using Skyrim 1.5.97 and the current skse version

**Comment by ArranzCNL** [comment]
It has been stated many times, try MenuMode 0 or 1 and if it still fails install ReShade... the issue resides on the user end having external tools active on the system or even been messing with Steam itself.

Now I am no graphics expert (never said I was) but I know ReShade fixes whatever issue is happening. It would be nice if Bethesda would give me a break and stop updating the damn 10yr old game for no apparent reason I could actually research into it and other stuff instead of rewriting Improved Camera (third time now!)... Hint apparently there is another update coming but I think if it breaks IC again, I will only support 1.5.97/1.6.640/1.6.659.

**Comment by murderman2** [comment]
Thank you, I understand your frustration.
