### ISSUE TITLE
The direction of FirstPerson'View do not follow the third party Scripted animations 

### ISSUE THREAD

**Issue by Lurker1011** [ArranzCNL/ImprovedCameraSE#16]
description:
some third party animations may change direction of the player's face, the old version of improvedCamera can make the direction of face following the third party Scripted animations, but new version do not 

i found it when i test improvedCamera PR2 with Osex/Ostim,

screenshot:

https://github.com/Lurker1011/Image/blob/main/The%20Elder%20Scrolls%20V%20Skyrim%20Special%20Edition_2022.06.25-18.57.png?raw=true

the view is stuck to the north when the animation change player's direction to the south.
improvedCamera BETA 4 with default ini dont have this issue

may be fixed by changing improvedCameraSE.ini, but i dont find which setting can affect it.

**Comment by ArranzCNL** [comment]
Yeah this only affects nsfw mods, it is on the radar.
I briefly looked at OSex and it gets stuck in the sitting detection state for first person, which obviously shouldn't happen.

I'm going to write support for them differently similar to how the animation state is handled for Shake It, Skyrim's Got Talent (bard stuff), currently it isn't a priority as focus is now on AE PR.

Hoping to get the support in for at least OSex before Nexus release, since it is pretty simple to get up and running. (2-3 mods)

**Comment by ArranzCNL** [comment]
Work is completed, carrying out tests:
- ~~OSex~~ Note: Player Always Dom needs to be selected otherwise your character will go into the background.
- ~~SexLabs~~

**Comment by ArranzCNL** [comment]
Sexlab detection implemented.
