### ISSUE TITLE
Werewolf Transformation

### ISSUE THREAD

**Issue by xLaReL** [ArranzCNL/ImprovedCameraSE#57]
Hello!

What that title says is that during transformation to werewolf, **the body disappears or becomes invisible** in 1st and in 3rd person.

Tested the werewolf transformation with Improved Camera and without.. And the result is, if I disable Improved Camera, the body is there (you can see the transformation in process).

**Comment by ArranzCNL** [comment]
For first person, viewing of the body has been disabled due to how crazy the animation is.

You can see it occur as normal in third person if you change:
bEventTransform=0

*rant*
After all these updates bethesda has done to Skyrim, you would have thought they'd have fixed the werewolf animations and vampirelord (node mislabel).
