### ISSUE TITLE
NearDistance Breaks ENB Water Reflections

### ISSUE THREAD

**Issue by EonTitan277** [ArranzCNL/ImprovedCameraSE#58]
When passing the NearDistancePitchThreshold, ENB water reflections suddenly become very opaque. Increasing the NearDistance setting to compensate causes body clipping, so that isn't a solution.
Interestingly, Immersive First Person View doesn't really have this issue. Even with its NearClipExteriorDown setting at 1 (default is 3 but I usually use 8), the most disturbance is minor reflection flickering.
I am currently using ENBSeries v0.483 with Skyrim SE 1.5.97.

**Comment by ArranzCNL** [comment]
It is a known limitation for now unfortunately. I don't know enough about the engine how the NearDistance works as interiors it seems fine but exterior depending on graphical mods installed the opaqueness of water and shadows flickering can be very annoying!!!

IFPV works differently as it mimicks First Person by using the Third Person camera. IC only mimicks First Person where it has too, horse riding, werewolf, vampirelord etc. Why the mods are different.

**Comment by EonTitan277** [comment]
I don't know what I did, but the issue is gone at the moment.
Things that changed with my game recently:
- Uninstalled Water for ENB. (I use RW2 and wanted to try the Water for ENB textures. The issue could have been that I had forgotten to disable the Water for ENB meshes when I was still using the mod and they were causing the issue?)
     -  Note: (I just reinstalled Water for ENB, disabled its esps, and kept the meshes to test it. The problem did not return, so maybe that wasn't causing the issue after all.)

- Gerating LODs with DynDOLOD 3. (No clue how that could fix it.)
- Updated a few mods that I can't remember.
- The game weather changed over time. (The weather may have been part of the cause I guess.)

**Comment by ArranzCNL** [comment]
Is this what you mean. As you can see from my screenshots it doesn't look too bad due to my mod setup, if it was bog standard vanilla the water would look opaque. Both screenshots are taken with Water for ENB and using Rudy ENB Obsidian Weathers preset.

No Adjustment is Improved Camera's values at default. The other I adjusted NearDistancePitchThreshold until it kicked in.


This one would cause opaque water if vanilla setup.
![water_adjustment](https://user-images.githubusercontent.com/52199624/208477020-5af8679d-2c55-4978-8908-099d7571affe.png)

No adjustment done to default config of Improved Camera
![water_no_adjustment](https://user-images.githubusercontent.com/52199624/208478482-dcf17c53-eb17-4459-b088-19f939bbced9.png)

**Comment by EonTitan277** [comment]
Looks kinda like it, but I wasn't using vanilla water.
Also, I was using Silent Horizons ENB with modified water settings, so mine looked more opaque than the screenshot. But like I said in the last comment, the problem went away and I don't know why. So far, it hasn't come back yet.
