### ISSUE TITLE
Incompatibility with Movement Behavior Overhaul?

### ISSUE THREAD

**Issue by wapak509** [ArranzCNL/ImprovedCameraSE#66]
I like to switch between first and third-person, but when using the latest build from September 5 with MBO, left and right direction input seems to be disabled in third person. Forward and backward work okay, and in first-person and even third-person with weapon unsheathed, character can move in all directions just fine. Just disabling/enabling Improved Camera will fix/reactivate the issue. 

If I use the PR4 build from August 14, left and right movement will work but MBO's left-to-right transition animation will not, which is the main reason for me to use MBO.

I didn't notice for a long time since True Directional Movement was hiding the problem since it uses rotate+forward instead of left/right, but the issue will still be there if I change the Directional Movement option in TDM's MCM to Vanilla.

**Comment by ArranzCNL** [comment]
Looked into this.

This specific issue is due to MBO and TDM, pretty much have to choose one or the other, or put up with the issue in first person.
MBO relies on TDM if using that version, TDM isn't activated in first person which in turn means the animations are not playing.

As even the video demostrates MBO + IC work fine together but when you start throwing other things into the mixer well some things just have to be ignored as it is impossible to get everything working 100% together.

As for affecting third person IC doesnt work like IFPV so third person is only touched upon specific times, general movement/combat is not one of them.

**Comment by wapak509** [comment]
Thanks for looking into it. I've removed MBO and found that increasing the controller buffer a bit in Improved Camera's menu basically has the effect I want in removing the jerky side-to-side snapping.
