### ISSUE TITLE
Crash in the title interface

### ISSUE THREAD

**Issue by hikawasayotohina** [ArranzCNL/ImprovedCameraSE#68]
Seems to be random

Sorry, I can only provide logs
[Crash_2022_12_10_17-6-40.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/10214060/Crash_2022_12_10_17-6-40.txt)
[Crash_2022_12_12_0-9-58.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/10214061/Crash_2022_12_12_0-9-58.txt)
[Crash_2022_12_13_11-33-31.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/10214062/Crash_2022_12_13_11-33-31.txt)

**Comment by ArranzCNL** [comment]
That error should be fixed in the upcoming build as I think it was due to CoInitialize which I use for IShellItem2 to retrieve other mods dll information either way I've placed a failsafe around it.

It might be a Discord issue which can randomly crash IC at startup then it is fine. I reported an issue with discord over 2yrs ago so if it is on discords end it won't ever get fixed! Fun fact: if you have the menu loaded as overlay discord injects into that instead of the game.
